### PR TITLE
added spotbugs to project.

### PR DESCRIPTION
**Pull request by atreichl**

### CODE REVIEW

**Comment by atreichl** [comment]
use gradle spotbugsDebug to run it. Will only run after changes are made to code since it's last run.

**Comment by mccodav1** [comment]
Will this run during GitHub Actions at all?

**Comment by atreichl** [comment]
spotbugs does, you can see it during the gradle build part of the android CI.

**Comment by atreichl** [comment]
I have also added pmd to the project.

**Comment by fmehdad97** [comment]
I tried running this. If I am not mistaken, the report generated is found under build/report/spotbugs?
It shows me no bugs found... Which I think might be a mistake. 

Also, can we please try to integrate https://find-sec-bugs.github.io/ also? I think it will be a very worthwhile addition.

**Comment by atreichl** [comment]
The report is in app\build\reports\spotbugs. I just deleted it and ran spotbugsdebug again and my report has 138 errors in it. I added find-sec-bugs it is part of the spotbugs report they was only 1 bug it found for me.

**Review by fmehdad97 — APPROVED** [review]
Re-ran the command on a Windows machine and found to be working.

Requesting only one change to update the Readme.MD to reflect the following:
1. How to run spotBugs. I believe the comment in the PR which tells you how to run it "gradle spotbugsDebug" might get lost in the future
2. a reference to the rules used (if possible)
3. Where the report is generated

I highly recommend the above be added to README before merging to dev to save dev time looking for the instructions in the future.

Also, post-optimization, our code-base generated 64 bugs now compared to the 129 before I merged in dev in my local branch.

**Pull request merged**
