### PR TITLE
Remember me

### PR DESCRIPTION
**Pull request by mccodav1**

### CODE REVIEW

**Review by atreichl — CHANGES_REQUESTED** [review]
The remember me functionality works. I will approve once you add back the placeholder poste.txt file so the GitHub build does not fail.

**Comment by mccodav1** [comment]
> The remember me functionality works. I will approve once you add back the placeholder poste.txt file so the GitHub build does not fail.

We need to remove poste.txt from tracking somehow, this is going to be a pain through semester two. Just noticed this, pushing it up now.

**Review by atreichl — APPROVED** [review]
looks good to go now. could we not added poste.txt to .gitignore so that local changes to it will be ignored?

**Comment by fmehdad97** [comment]
image

So i came across this while testing other things. 
If you clicked remember me, and then deleted the user, or the token, or the database (in my case I deleted the database), the user no longer exists but the application keeps you logged into the ghost account and shown above is the log that it returns. I think it might be beneficial to add that check in, especially as we start thinking about the multiplatform aspect of the application

**Pull request merged**
